FROM amd64/ubuntu:20.04

LABEL mantainer="Paolo Tomasin <pooltomasin@hotmail.com>"
LABEL mantainer="Valerio Magnago <valerio.magnago@gmail.com>"

#refs: https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Development-Setup/ 
#refs: https://github.com/DynoRobotics/dyno-docker-images/blob/master/balena-amd64-ros2/dashing-isolated-cyclone/Dockerfile

# environment vars
ENV ROS_DISTRO foxy
ENV ROS2_WS /opt/ros2_ws
ENV ROS_CMAKE_BUILD_TYPE Release


# setup entrypoint
#COPY entrypoint.sh /
#ENTRYPOINT ["/entrypoint.sh"]

#CMD ["bash"]

