# This is a basic workflow to help you get started with Actions

#refs: (https://github.com/marketplace/actions/docker-buildx#build-and-push-to-dockerhub)
#refs: (https://stevenmortimer.com/running-github-actions-sequentially/#an-example)

name: buildx maila-base to DockerHub with cache

on:
  workflow_dispatch:  
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-maila-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-maila-base
      -
        name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=false" \
            --tag maila/maila-base:latest \
            --file ./maila-base/Dockerfile ./maila-base
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker Buildx (push)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag maila/maila-base:latest \
            --file ./maila-base/Dockerfile ./maila-base
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect maila/maila-base:latest
      -
        name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: build-maila-base-done
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'


