# This is a basic workflow to help you get started with Actions

#refs: (https://github.com/marketplace/actions/docker-buildx#build-and-push-to-dockerhub)
#refs: (https://stevenmortimer.com/running-github-actions-sequentially/#an-example)

name: buildx maila-dev to DockerHub with cache

on:
  repository_dispatch:
    types: [build-maila-base-done]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-maila-dev-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-maila-dev
      -
        name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=false" \
            --tag maila/maila-dev:latest \
            --file ./maila-dev/Dockerfile ./maila-dev
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker Buildx (push)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag maila/maila-dev:latest \
            --file ./maila-dev/Dockerfile ./maila-dev
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect maila/maila-dev:latest
