# This is a basic workflow to help you get started with Actions

name: Build and push maila-dev Docker images

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    # https://stevenmortimer.com/running-github-actions-sequentially/#an-example
    types: [trigger-ubuntu-focal-ros2-foxy]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Checkout code
        uses: actions/checkout@v2

      # Build maila/maila-dev image
      - name: Build maila-dev docker images using cache
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./maila-dev
          dockerfile: Dockerfile
          image_name: maila/maila-dev
          image_tag: latest


