# This is a basic workflow to help you get started with Actions

name: Build and push ubuntu-focal-ros2-foxy Docker images

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    tags:
      - v*
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Checkout code
        uses: actions/checkout@v2

      # Build maila/ubuntu-focal-ros2-foxy image
      - name: Build maila/ubuntu-focal-ros2-foxy docker images using cache
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./ubuntu-focal-ros2-foxy
          dockerfile: Dockerfile
          image_name: maila/ubuntu-focal-ros2-foxy
          image_tag: latest

      # https://stevenmortimer.com/running-github-actions-sequentially/#an-example
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-ubuntu-focal-ros2-foxy
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
